openapi: 3.0.0
info:
  title: API de RPAccess
  version: 1.0.0
  description: Documentation de l'API de RPAccess.
servers:
  - url: https://backend-rpaccess-production.up.railway.app
    description: Serveur de production

paths:
  /aa/launch:
    post:
      tags:
        - Automation Anywhere
      summary: Lance un bot Automation Anywhere
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Succès

  /google/auth:
    get:
      tags:
        - Google
      summary: Authentifie avec Google
      responses:
        "200":
          description: Authentifié

  /zendesk/ticket:
    post:
      tags:
        - Zendesk
      summary: Crée un ticket Zendesk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "201":
          description: Ticket créé

  /psql/query:
    post:
      tags:
        - PSQL
      summary: Exécute une requête PSQL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Résultat de la requête
